version: '3.3'

services:
  db:
    image: mariadb
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
      # - ./themes:/var/www/html/wp-content/themes
      - .:/var/www/html/wp-content/plugins/leaflet-map
    ports:
      - 1234:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  
  cli:
    build: .
    depends_on:
      - wordpress
    volumes: 
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/leaflet-map
    environment:
      WORDPRESS_PORT: 1234

volumes:
  wp_db:
  wordpress: